########################################################
### Frequently used paths
########################################################
# define the paths to the frequently used folders
# Use to avoid hardcoding paths in the code!!!!
# think about it: do you prefer to modify a path once here, or correct a million hardcoded paths everywhere in the code?

# the path toward the root for all experiment data
datapath = "C:/pyctrl_data"

# the path toward the root for all experiment data
labjournalpath = "C:/pyctrl_labjournal"

# the path toward the log files
logspath = "C:/pyctrl_logs"

# the path toward the quantum machine configuration file
qmconfigpath = "C:/pyctrl/configs/qm_base_config.toml"